# Generated by Django 6.0.5 on 2026-05-27 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripción', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(max_length=200)),
                ('Ingredientes', models.TextField()),
                ('Pasos_de_elaboración', models.TextField()),
                ('Tiempo_de_preparación', models.CharField(max_length=50)),
                ('Región', models.CharField(choices=[('mondstadt', 'Mondstadt'), ('liyue', 'Liyue'), ('inazuma', 'Inazuma'), ('sumeru', 'Sumeru'), ('fontaine', 'Fontaine'), ('natlan', 'Natlan'), ('snezhnaya', 'Snezhnaya')], max_length=100)),
                ('Rareza', models.PositiveIntegerField(help_text='Estrellas del 1 al 5')),
                ('Fecha_de_creación', models.DateTimeField(auto_now_add=True)),
                ('Imagen_url', models.URLField(blank=True, null=True)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.TextField()),
                ('Fecha_de_publicación', models.DateTimeField(auto_now_add=True)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Receta_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario_de_teyvat.receta')),
            ],
        ),
    ]
