# Generated by Django 6.0.5 on 2026-05-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario_de_teyvat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='Imagen_url',
        ),
        migrations.AddField(
            model_name='receta',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
    ]
