# Generated by Django 6.0.5 on 2026-06-03 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario_de_teyvat', '0002_remove_receta_imagen_url_receta_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario_de_teyvat.receta')),
            ],
            options={
                'unique_together': {('Receta', 'Autor')},
            },
        ),
    ]
